name: Deploy do Sistema de Estoque

on:
  push:
  branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build da imagem Docker
        run: docker build -t estoque-api .

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/projeto-estoque
            git pull origin main
            docker compose down               
            docker compose up -d --build      